name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt install autopoint check intltool libexpat1-dev pkg-config
    - name: configure
      run: |
        test -f config.rpath || touch config.rpath
        sh ./autogen.sh
        ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
